multipart:
  max-file-size: 10MB
  max-request-size: 10MB
datasource:
  url: jdbc:mysql://localhost:3306/winwin?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
  username: root
  password: root
  driver-class-name: com.mysql.cj.jdbc.Driver
jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      format_sql: true
      show_sql: true
      default_batch_fetch_size: 100

server:
  servlet:
    context-path: /dev

swagger:
  url: http://localhost:8080/dev

jwt:
  secret: jwtscretjwtscretjwtscretjwtscretjwtscretjwtscretjwtscretjwtscretjwtscretjwtscretjwtscretjwtscretjwtscret
  expiration-period: 10000